name: admin workflow

on:
  pull_request:
    branches:
      - stage
      - main
    types:
      - closed
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  MANIFESTS_REPO_TOKEN: ${{ secrets.MANIFESTS_REPO_TOKEN }}
jobs:
  build_and_test:
    # closed event triggered by merged PRs only
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: setup node js enviroment
        uses: actions/setup-node@v6
        with:
          node-version: "22.21.0"

      - name: Install Dependancies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Test application
        run: npm run test

  docker_image_build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build_and_test

    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: set_tag
        run: echo "tag=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        run: |
          TAG=${{ steps.set_tag.outputs.tag }}
          if [ "${{ github.ref_name }}" = "main" ]; then
            IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/admin:${TAG}"
          else
            IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/stage-admin:${TAG}"
          fi
          echo "Building and pushing image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  update_manifests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: docker_image_build_and_push

    steps:
      - name: Checkout manifests repo
        run: |
          git clone https://x-access-token:${{ env.MANIFESTS_REPO_TOKEN }}@github.com/KavinduGD/portfolio-manifests.git
          cd portfolio-manifests
          git checkout main

      - name: Update admin image tag
        run: |
          cd portfolio-manifests

          TAG="${{ needs.docker_image_build_and_push.outputs.image_tag }}"

          if [ "${{ github.ref_name }}" = "main" ]; then
            sed -i "s|image: kavinduorg/admin:.*|image: kavinduorg/admin:${TAG}|" ./prod/admin-patch.yaml
          else
            sed -i "s|image: kavinduorg/stage-admin:.*|image: kavinduorg/stage-admin:${TAG}|" ./stage/admin-patch.yaml
          fi

      - name: Commit and push changes
        run: |
          cd portfolio-manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add .
          git commit -m "chore: update admin image to ${{ needs.docker_image_build_and_push.outputs.image_tag }}"
          git push origin main
