name: backend workflow

on:
  pull_request:
    branches:
      - stage
      - main
    types:
      - closed
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_test:
    # closed event triggered by merged PRs only
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: setup node js enviroment
        uses: actions/setup-node@v6
        with:
          node-version: "22.21.0"

      - name: Install Dependancies
        run: npm ci

      - name: Build application
        run: npm run build

  docker_image_build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::10}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/admin:${TAG}"
          else
            IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/stage-admin:${TAG}"
          fi
          echo "Building and pushing image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
